import { useState } from 'react';
import { motion } from 'framer-motion';
import Layout from '../components/layout/Layout';
import { toast } from '../components/ui/Toast';
import { useAuthStore } from '../hooks/useAuth';
import { useWeeklyAnalytics } from '../hooks/useHealthData';
import api from '../services/api';

interface ReportSection {
  title: string;
  icon: string;
  color: string;
  data: { label: string; value: string | number; unit?: string }[];
}

export default function Reports() {
  const { user }              = useAuthStore();
  const { analytics, loading } = useWeeklyAnalytics();
  const [generating, setGenerating] = useState(false);
  const [format, setFormat]   = useState<'json' | 'txt' | 'csv'>('txt');
  const [period, setPeriod]   = useState<'week' | 'month'>('week');

  const sections: ReportSection[] = [
    {
      title: 'Sleep',
      icon: '😴',
      color: '#60a5fa',
      data: [
        { label: 'Avg Duration',  value: analytics?.avgSleepDuration ?? 0, unit: 'hrs' },
        { label: 'Logs This Week', value: analytics?.logsThisWeek ?? 0 },
      ],
    },
    {
      title: 'Mood & Mental',
      icon: '😊',
      color: '#a78bfa',
      data: [
        { label: 'Avg Mood Rating',  value: analytics?.avgMoodRating ?? 0, unit: '/ 5' },
        { label: 'Wellness Score',   value: analytics?.avgWellnessScore ?? 0 },
      ],
    },
    {
      title: 'Fitness',
      icon: '🏋️',
      color: '#fb923c',
      data: [
        { label: 'Total Workouts', value: analytics?.totalWorkouts ?? 0 },
      ],
    },
    {
      title: 'Hydration',
      icon: '💧',
      color: '#34d399',
      data: [
        { label: 'Avg Hydration', value: analytics?.avgHydration ?? 0, unit: 'L/day' },
      ],
    },
  ];

  const buildTextReport = () => {
    const now  = new Date().toLocaleString('en-IN');
    const lines: string[] = [
      '============================================================',
      '         HealthTrack360 AI — Wellness Report',
      '============================================================',
      `User    : ${user?.name}`,
      `Email   : ${user?.email}`,
      `Period  : This ${period}`,
      `Generated: ${now}`,
      '------------------------------------------------------------',
      '',
      '  WELLNESS OVERVIEW',
      '------------------------------------------------------------',
      `  Overall Score   : ${analytics?.avgWellnessScore ?? '—'}`,
      `  Days Logged     : ${analytics?.logsThisWeek ?? 0}`,
      '',
      '  SLEEP',
      `  Avg Duration    : ${analytics?.avgSleepDuration ?? 0} hrs`,
      '',
      '  MOOD & MENTAL',
      `  Avg Mood Rating : ${analytics?.avgMoodRating ?? 0} / 5`,
      '',
      '  FITNESS',
      `  Total Workouts  : ${analytics?.totalWorkouts ?? 0}`,
      '',
      '  HYDRATION',
      `  Avg Daily Intake: ${analytics?.avgHydration ?? 0} L`,
      '',
      '------------------------------------------------------------',
      '  WEEKLY TREND',
      '------------------------------------------------------------',
      ...(analytics?.weeklyTrend || []).map((t: any) =>
        `  ${new Date(t.date).toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short' })}  →  Score: ${t.score}`
      ),
      '',
      '============================================================',
      '  This report is generated by HealthTrack360 AI.',
      '  Not a substitute for professional medical advice.',
      '============================================================',
    ];
    return lines.join('\n');
  };

  const buildCSV = () => {
    const rows = [
      ['Date', 'Wellness Score'],
      ...(analytics?.weeklyTrend || []).map((t: any) => [
        new Date(t.date).toLocaleDateString('en-IN'),
        t.score,
      ]),
    ];
    return rows.map(r => r.join(',')).join('\n');
  };

  const buildJSON = () => {
    return JSON.stringify({
      user:      { name: user?.name, email: user?.email },
      period,
      generatedAt: new Date().toISOString(),
      analytics: {
        avgWellnessScore: analytics?.avgWellnessScore,
        avgSleepDuration: analytics?.avgSleepDuration,
        avgMoodRating:    analytics?.avgMoodRating,
        totalWorkouts:    analytics?.totalWorkouts,
        avgHydration:     analytics?.avgHydration,
        logsThisWeek:     analytics?.logsThisWeek,
        weeklyTrend:      analytics?.weeklyTrend,
      },
    }, null, 2);
  };

  const downloadReport = () => {
    setGenerating(true);
    try {
      let content  = '';
      let filename = '';
      let mimeType = '';
      const date   = new Date().toISOString().split('T')[0];

      if (format === 'txt') {
        content  = buildTextReport();
        filename = `HealthTrack360_Report_${date}.txt`;
        mimeType = 'text/plain';
      } else if (format === 'json') {
        content  = buildJSON();
        filename = `HealthTrack360_Report_${date}.json`;
        mimeType = 'application/json';
      } else {
        content  = buildCSV();
        filename = `HealthTrack360_Report_${date}.csv`;
        mimeType = 'text/csv';
      }

      const blob = new Blob([content], { type: mimeType });
      const url  = URL.createObjectURL(blob);
      const a    = document.createElement('a');
      a.href     = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast(`Report downloaded as ${filename} ✓`, 'success');
    } catch {
      toast('Failed to generate report', 'error');
    } finally {
      setGenerating(false);
    }
  };

  const copyToClipboard = () => {
    const text = buildTextReport();
    navigator.clipboard.writeText(text)
      .then(() => toast('Report copied to clipboard ✓', 'success'))
      .catch(() => toast('Copy failed', 'error'));
  };

  return (
    <Layout>
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-6">
        <h1 className="text-3xl font-bold text-white">📄 Reports & Export</h1>
        <p className="text-gray-400 mt-1">Generate and download your wellness reports.</p>
      </motion.div>

      {/* Report Options */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6 max-w-3xl">
        {/* Period */}
        <div className="rounded-2xl p-5 border border-white/8" style={{ background: 'rgba(255,255,255,0.03)' }}>
          <p className="text-white font-semibold mb-3">📅 Report Period</p>
          <div className="flex gap-2">
            {(['week', 'month'] as const).map(p => (
              <button key={p} onClick={() => setPeriod(p)}
                className="flex-1 py-3 rounded-xl text-sm font-semibold capitalize transition-all"
                style={period === p
                  ? { background: 'linear-gradient(135deg,#3b82f6,#1d4ed8)', color: 'white' }
                  : { background: 'rgba(255,255,255,0.05)', color: '#9ca3af', border: '1px solid rgba(255,255,255,0.08)' }}>
                This {p}
              </button>
            ))}
          </div>
        </div>

        {/* Format */}
        <div className="rounded-2xl p-5 border border-white/8" style={{ background: 'rgba(255,255,255,0.03)' }}>
          <p className="text-white font-semibold mb-3">📦 Export Format</p>
          <div className="flex gap-2">
            {([
              { key: 'txt',  label: '📄 TXT',  desc: 'Readable'  },
              { key: 'csv',  label: '📊 CSV',  desc: 'Spreadsheet' },
              { key: 'json', label: '🔧 JSON', desc: 'Developer'  },
            ] as const).map(f => (
              <button key={f.key} onClick={() => setFormat(f.key)}
                className="flex-1 py-2.5 rounded-xl text-xs font-semibold transition-all flex flex-col items-center gap-0.5"
                style={format === f.key
                  ? { background: 'rgba(96,165,250,0.2)', border: '1px solid rgba(96,165,250,0.4)', color: '#60a5fa' }
                  : { background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', color: '#6b7280' }}>
                <span>{f.label}</span>
                <span className="text-xs opacity-60">{f.desc}</span>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Preview */}
      <div className="max-w-3xl mb-6">
        <div className="rounded-2xl border border-white/8 overflow-hidden" style={{ background: 'rgba(255,255,255,0.02)' }}>
          <div className="flex items-center justify-between px-5 py-3 border-b border-white/5">
            <p className="text-white font-semibold text-sm">👁 Report Preview</p>
            <div className="flex items-center gap-2">
              <span className="text-xs text-gray-500">
                {user?.name} · This {period} · {format.toUpperCase()}
              </span>
            </div>
          </div>

          {loading ? (
            <div className="p-5 space-y-2">
              {[...Array(4)].map((_, i) => <div key={i} className="h-4 shimmer rounded" />)}
            </div>
          ) : (
            <div className="p-5">
              {/* Summary cards */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">
                {[
                  { label: 'Wellness Score',  value: analytics?.avgWellnessScore ?? 0, icon: '💚', color: '#34d399' },
                  { label: 'Avg Sleep',        value: `${analytics?.avgSleepDuration ?? 0}h`, icon: '😴', color: '#60a5fa' },
                  { label: 'Avg Mood',         value: `${analytics?.avgMoodRating ?? 0}/5`, icon: '😊', color: '#a78bfa' },
                  { label: 'Workouts',         value: analytics?.totalWorkouts ?? 0, icon: '🏋️', color: '#fb923c' },
                ].map((s, i) => (
                  <motion.div key={s.label} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: i * 0.07 }}
                    className="rounded-xl p-3 text-center border border-white/5"
                    style={{ background: `${s.color}11` }}>
                    <span className="text-xl block mb-1">{s.icon}</span>
                    <p className="text-lg font-black" style={{ color: s.color }}>{s.value}</p>
                    <p className="text-xs text-gray-600 mt-0.5">{s.label}</p>
                  </motion.div>
                ))}
              </div>

              {/* Sections */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {sections.map((sec, i) => (
                  <motion.div key={sec.title} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.06 }}
                    className="rounded-xl p-4 border border-white/5"
                    style={{ background: `${sec.color}08` }}>
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-xl">{sec.icon}</span>
                      <p className="text-white font-semibold text-sm">{sec.title}</p>
                    </div>
                    {sec.data.map(d => (
                      <div key={d.label} className="flex justify-between text-xs py-1 border-b border-white/[0.04] last:border-0">
                        <span className="text-gray-400">{d.label}</span>
                        <span className="font-bold" style={{ color: sec.color }}>{d.value}{d.unit ? ` ${d.unit}` : ''}</span>
                      </div>
                    ))}
                  </motion.div>
                ))}
              </div>

              {/* Weekly trend table */}
              {analytics?.weeklyTrend?.length > 0 && (
                <div className="mt-4 rounded-xl border border-white/5 overflow-hidden"
                  style={{ background: 'rgba(255,255,255,0.02)' }}>
                  <p className="text-xs text-gray-500 px-4 py-2 border-b border-white/5 font-medium uppercase tracking-wide">Weekly Trend</p>
                  <table className="w-full text-xs">
                    <thead>
                      <tr>
                        <th className="text-left px-4 py-2 text-gray-600 font-medium">Date</th>
                        <th className="text-right px-4 py-2 text-gray-600 font-medium">Score</th>
                        <th className="text-right px-4 py-2 text-gray-600 font-medium">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {analytics.weeklyTrend.map((t: any, i: number) => {
                        const s = t.score;
                        const c = s >= 70 ? '#34d399' : s >= 50 ? '#fbbf24' : '#f87171';
                        return (
                          <tr key={i} className="border-t border-white/[0.03]">
                            <td className="px-4 py-2 text-gray-400">
                              {new Date(t.date).toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short' })}
                            </td>
                            <td className="px-4 py-2 text-right font-bold" style={{ color: c }}>{s}</td>
                            <td className="px-4 py-2 text-right">
                              <span className="text-xs px-2 py-0.5 rounded-full"
                                style={{ background: `${c}20`, color: c }}>
                                {s >= 70 ? 'Good' : s >= 50 ? 'Fair' : 'Low'}
                              </span>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-wrap gap-3 max-w-3xl">
        <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
          onClick={downloadReport} disabled={generating || loading}
          className="btn-primary px-8 py-3 text-base disabled:opacity-50">
          {generating ? '⟳ Generating...' : `⬇️ Download ${format.toUpperCase()} Report`}
        </motion.button>
        <button onClick={copyToClipboard} className="btn-secondary px-6 py-3">
          📋 Copy to Clipboard
        </button>
        <button
          onClick={() => window.print()}
          className="btn-secondary px-6 py-3">
          🖨️ Print Report
        </button>
      </div>

      {/* Tips */}
      <div className="mt-6 max-w-3xl rounded-2xl p-4 border border-blue-500/15"
        style={{ background: 'rgba(59,130,246,0.05)' }}>
        <p className="text-blue-300 font-semibold text-sm mb-2">💡 About Your Reports</p>
        <div className="space-y-1">
          {[
            'TXT format is best for reading and sharing with a healthcare provider',
            'CSV format opens directly in Excel, Google Sheets or Numbers',
            'JSON format is useful for developers or importing into other apps',
            'Reports are generated from your logged health data stored in MongoDB',
          ].map((tip, i) => (
            <p key={i} className="text-xs text-gray-400 flex gap-2">
              <span className="text-blue-400 shrink-0">•</span>{tip}
            </p>
          ))}
        </div>
      </div>
    </Layout>
  );
}
